apiVersion: v1
kind: Pod
metadata:
  namespace: srt-link-bot
  name: srt-link-bot
  labels:
    name: srt-link-bot
spec:
  containers:
  - name: srt-link-bot
    image: repo.lab.hq.solidrust.net:5000/srt-link-bot:1.0.0
# Egress config
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: srt-link-bot
  name: srt-link-bot-egress
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress