apiVersion: v1
kind: Pod
metadata:
  name: srt-link-bot
  labels:
    name: srt-link-bot
spec:
  containers:
  - name: srt-link-bot
    image: repo.lab.hq.solidrust.net:5000/srt-link-bot:1.0.0