apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-operator-ui
  namespace: default
  labels:
    application: postgres-operator-ui
spec:
  rules:
    - host: psql.lab.hq.solidrust.net
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: postgres-operator-ui
                port:
                  number: 80
  tls: 
    - hosts: 
        - psql.lab.hq.solidrust.net
      secretName: star.lab.hq.solidrust.net-tls