apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv1
spec:
  storageClassName: redis-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv2
spec:
  storageClassName: redis-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv3
spec:
  storageClassName: redis-local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data3"